selective listing for -l option

diff --git a/jmpdir b/jmpdir
--- a/jmpdir
+++ b/jmpdir
@@ -51,7 +51,7 @@ if [ "$1" = "--help" -o "$1" = "-h" ]; then
     echo "      5) Search"
     echo ""
     echo "        * 'jds' OR 'jd -s' to search a directory"
-    echo "        * Input a pattern which can be grepped"
+    echo "        * Input pattern(s) which can be grepped"
     echo "        * If only one search result, will jmp to that dir" 
     echo ""
 #clearing
@@ -70,10 +70,12 @@ elif [ "$1" = "-j" ]; then
     pwd
 #removing
 elif [ "$1" = "-r" ]; then
+    #no extra parameter; removing curr-dir from list
     if [ $# == 1 ]; then
         curr=`pwd`
         record=`grep -n "$curr\$" ~/.dirlist | awk -F: '{print $1}'`
         sed -i "${record} d" ~/.dirlist
+    #removing the number provided
     elif [ $# == 2 ]; then
         temp=`awk -v f2=$2 'BEGIN{comp=f2} {if (NR == comp) print}' ~/.dirlist`
         if [ "$temp" = "" ]; then
@@ -90,7 +92,11 @@ elif [ "$1" = "-l" ]; then
         echo "Directory list is empty"
         echo ""
     else
-        cat -n ~/.dirlist | less
+       if [ $# == 2 ]; then
+          cat -n ~/.dirlist | /bin/grep $2
+       else # if [ $# == 1 ];
+          cat -n ~/.dirlist | less
+       fi
     fi
 #preving
 elif [ "$1" = "-" ]; then
@@ -100,13 +106,53 @@ elif [ "$1" = "-" ]; then
    pwd
 #searching
 elif [ "$1" = "-s" ]; then
-   no_records=`cat ~/.dirlist | /bin/grep -n $2 | wc -l`
-	if [ $no_records == 1 ]; then
-		prev=`pwd`
-		cd `cat ~/.dirlist | /bin/grep $2`
-	else
-		cat ~/.dirlist | /bin/grep -n $2
-	fi
+   # searching when you know two substrings
+   if [ $# == 3 ]; then
+      no_records=`cat ~/.dirlist | /bin/grep -n $2 | /bin/grep $3 | wc -l`
+      if [ $no_records == 1 ]; then
+         prev=`pwd`
+         cd `cat ~/.dirlist | /bin/grep $2 | /bin/grep $3`
+         pwd
+      elif [ $no_records == 0 ]; then
+         echo "No match found"
+      else
+         cat ~/.dirlist | /bin/grep -n $2 | /bin/grep $3
+      fi
+   else # searching when you know one substring
+      no_records=`cat ~/.dirlist | /bin/grep -n $2 | wc -l`
+      if [ $no_records == 1 ]; then
+         prev=`pwd`
+         cd `cat ~/.dirlist | /bin/grep $2`
+         pwd
+      elif [ $no_records == 0 ]; then
+         echo "No match found"
+      else
+         cat ~/.dirlist | /bin/grep -n $2
+      fi
+   fi
+#recursive adding
+elif [ "$1" = "-R" ]; then
+   prev=`pwd`
+   if (( $# <= 1 )); then
+      echo "Error: No parameter"
+   else
+      cd $2
+   fi
+   curr=`pwd`
+   grep "$curr\$" ~/.dirlist > /dev/null 
+   if [ $? == 1 ]; then
+      pwd >> ~/.dirlist
+   fi
+   cmd=`ls -ltrh | grep ^dr | awk '{print $9}'`
+   for i in $cmd; do
+      cd $i
+      curr=`pwd`
+      grep "$curr\$" ~/.dirlist > /dev/null 
+      if [ $? == 1 ]; then
+         pwd >> ~/.dirlist
+      fi
+      cd ..
+   done
 #adding
 else
     prev=`pwd`
